version: '3.8'

services:

  mongodb-0:
    container_name: mongodb-0
    hostname: mongodb-0
    image: mongo:4.4
    user: root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "37017:27017"
    volumes:
      - /data/mongo/data/mongo0:/data/db
    command: mongod --replSet rs0

  mongodb-1:
    container_name: mongodb-1
    hostname: mongodb-1
    image: mongo:4.4
    user: root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "37018:27017"
    volumes:
      - /data/mongo/data/mongo1:/data/db
    command: mongod --replSet rs0

  mongodb-2:
    container_name: mongodb-2
    hostname: mongodb-2
    image: mongo:4.4
    user: root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "37019:27017"
    volumes:
      - /data/mongo/data/mongo2:/data/db
    command: mongod --replSet rs0

  ycsb:
    container_name: ycsb
    hostname: ycsb
    build:
      context: ycsb
      args:
        - GIT_BRANCH=master
    environment:
      - WORKLOAD_NAME=read_mod_wrt
      - WORKLOAD_RECORD_COUNT=20000
